name: "Push Test"

on:
  workflow_dispatch:
  push:

jobs:
  push:
    name: "Push"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "VirusTotal"
        id: vt
        uses: cssnr/virustotal-action@files
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vt_api_key: ${{ secrets.VT_API_KEY }}
          file_globs: README.md

      - name: "Echo Results"
        run: echo ${{ steps.vt.outputs.results }}
